spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.37.141
    port: 6379
    password:
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
